account/urls.py
from django.urls import path

from . import views
app_name = 'account'
urlpatterns = [
    path('login/', views.custom_login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('auth-choice/', views.auth_choice_view, name='auth_choice'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.custom_logout_view, name='logout'),
]

astertek/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add-ajax/', views.cart_add_ajax, name='cart_add_ajax'),
    path('update-ajax/', views.cart_update_ajax, name='cart_update_ajax'),
    path('remove-ajax/', views.cart_remove_ajax, name='cart_remove_ajax'),

    path('checkout/', views.checkout_view, name='checkout'),
    path('checkout/process/', views.process_checkout, name='process_checkout'),
]

frontend/urls.py
from django.urls import path, include

from . import views
app_name = 'frontend'
urlpatterns = [
    path('', views.home, name='home'),
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),

    # path("categories/", views.category_list, name="category_list"),
    path("categories/<slug:slug>/", views.category_detail, name="category_detail"),
]

store/urls.py
from django.urls import path

from . import views
app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('search/', views.product_search, name='product_search'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
]

frontend/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404

# my imports
from store.models import Category, Product, Brand, Tag

def home(request):
    all_products = Product.objects.all()
    deals_products = Product.objects.filter(tags__name__iexact='Deals of the week', is_available=True)
    new_products = Product.objects.filter(tags__name__iexact='Recent Products', is_available=True)
    onsale_products = Product.objects.filter(tags__name__iexact='On Sale', is_available=True)
    featured_products = Product.objects.filter(tags__name__iexact='Featured Products', is_available=True)

    earphone_products = Product.objects.filter(tags__name__iexact='Ear Phones', is_available=True)
    mouse_products = Product.objects.filter(tags__name__iexact='Mouse', is_available=True)

    context = {
        'all_products': all_products,
        'deals_products': deals_products,
        'new_products': new_products,
        'onsale_products': onsale_products,
        'featured_products': featured_products,
        'earphone_products': earphone_products,
        'mouse_products': mouse_products,
    }
    return render(request, 'frontend/index.html', context)


# def category_list(request):
#     categories = Category.objects.all()
#     return render(request, "frontend/category_list.html", {"categories": categories})

def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    product_list = Product.objects.filter(category=category)

    # Pagination: 9 products per page (you can change this)
    paginator = Paginator(product_list, 15)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    brands = Brand.objects.all()
    tags = Tag.objects.all()

    context = {
        "category": category,
        'products': products,  # This is now a Page object
        'brands': brands,
        'tags': tags,
    }
    return render(request, "frontend/category_detail.html", context)


def about(request):
    return render(request, 'frontend/about.html' )


def contact(request):
    return render(request, 'frontend/contact.html' )

templates/frontend/include/navbar.html
{% load static %}

<!-- header area start -->
<header class="header_area">
    <!--header top start-->
    <div class="header_top bg-primary ">
        <div class="container">   
            <div class="row align-items-center">

                <div class="col-lg-6 col-md-6">
                    <div class="welcome_text">
                        <p class="text-white">Nigeria's Most Reliable Computers and Phones Online Store</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="top_right text-end">
                        <ul>
                           <li class=""><a href="{% url 'account:dashboard' %}" class="text-white">My Account</a>
                            </li> 
                            <!-- <li class="currency "><a href="#" class="text-white">USD <i class="ion-chevron-down"></i></a>
                                <ul class="dropdown_currency">
                                    <li><a href="#">EUR</a></li>
                                    <li><a href="#">BRL</a></li>
                                </ul>
                            </li> -->
                            <li class="language"><a href="#" class="text-white"><img src="{% static 'frontend/assets/img/logo/language.png' %}" alt=""> English <i class="ion-chevron-down"></i></a>
                                <ul class="dropdown_language">
                                    <li><a href="#"><img src="{% static 'frontend/assets/img/logo/cigar.jpg' %}" alt=""> French</a></li>
                                    <li><a href="#"><img src="{% static 'frontend/assets/img/logo/language2.png' %}" alt="">German</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>   
                </div>
            </div>
        </div>
    </div>
    <!--header top start-->
    
    <!--header middel start-->
    <div class="header_middel">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4">
                    <div class="logo">
                        <a href="{% url 'frontend:home' %}"><img src="{% static 'frontend/logos/logo.svg' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-5">
                    <div class="search_bar">
                        <form action="{% url 'store:product_search' %}">
                            {% csrf_token %}
                            <input placeholder="Search entire store here..." type="text" name="q"  value="{{ query|default:'' }}">
                            <button type="submit"><i class="ion-ios-search-strong"></i></button>
                        </form>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3">
                    <div class="cart_area">
                        <!-- <div class="wishlist_link">
                            <a href="#"><i class="ion-ios-heart-outline"></i></a>
                        </div> -->
                        <div class="cart_link">
                            <a href="{% url 'cart:cart_detail' %}"><i class="ion-ios-cart-outline"></i>My Cart</a>
                            <span class="cart_count" id="cart-count">{{ cart_item_count }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--header middel end-->
    
    <!--header bottom satrt-->
    <div class="header_bottom sticky-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-5">
                    <div class="categories_menu">
                        <div class="categories_title">
                            <h2 class="categori_toggle"> All categories</h2>
                        </div>
                        <div class="categories_menu_inner">
                            <ul>
                                {% for category in categories %}
                                    <li class="categorie_list">
                                        <a href="{{ category.get_absolute_url }}">
                                            {{ category.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                                <!-- <li><a href="#"> Accessories</a></li> -->
                                <!-- <li><a href="#"> Accessories</a></li>
                                <li><a href="#">Books & Office</a></li>
                                <li><a href="#"> Sport & Outdoor</a></li>
                                <li id="cat_toggle" class="has-sub"><a href="#"> More Categories</a>
                                    <ul class="categorie_sub">
                                        <li><a href="#"> Computer - Laptop</a></li>
                                    </ul>   

                                </li> -->
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 position-relative">
                    <div class="main_menu_inner">
                        <div class="main_menu d-none d-lg-block"> 
                            <ul>
                                <li class="active"><a href="{% url 'frontend:home' %}">Home</a>
                                </li>
                                <li><a href="{% url 'store:store' %}">Store</a>
                                </li>
                                <li><a href="{% url 'frontend:about' %}">About Us</a></li>
                                <li><a href="{% url 'frontend:contact' %}">Contact Us</a></li>
                                <li><a href="{% url 'account:register' %}">Register</a></li>
                                <li><a href="{% url 'account:login' %}">Login</a></li>
                            </ul>

                        </div>
                        <div class="mobile-menu d-lg-none">
                            <nav>  
                                <ul>
                                <li><a href="{% url 'frontend:home' %}"">Home</a>
                                </li>
                                <li><a href="{% url 'store:store' %}">Store</a>
                                </li>
                                <li><a href="{% url 'frontend:about' %}">About Us</a></li> 
                                <li><a href="{% url 'frontend:contact' %}">Contact Us</a></li>
                                <li><a href="{% url 'account:register' %}">Register</a></li>
                                <li><a href="{% url 'account:login' %}">Login</a></li>
                            </ul>
                            </nav>      
                        </div>
                    </div> 
                </div>
                <div class="col-lg-2">
                    <div class="contact_phone">
                        <div class="contact_icone">
                            <span class="pe-7s-headphones"></span>
                        </div>
                        <div class="contact_number">
                            <p>Call Us:</p>
                            <span>(+234)8039697424</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--header bottom end-->
</header>
<!--header area end-->