astertek/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add-ajax/', views.cart_add_ajax, name='cart_add_ajax'),
    path('update-ajax/', views.cart_update_ajax, name='cart_update_ajax'),
    path('remove-ajax/', views.cart_remove_ajax, name='cart_remove_ajax'),

    path('checkout/', views.checkout_view, name='checkout'),
    path('checkout/process/', views.process_checkout, name='process_checkout'),
]

frontend/urls.py
from django.urls import path, include

from . import views
app_name = 'frontend'
urlpatterns = [
    path('', views.home, name='home'),
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),

    # path("categories/", views.category_list, name="category_list"),
    path("categories/<slug:slug>/", views.category_detail, name="category_detail"),
]

store/urls.py
from django.urls import path

from . import views
app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('search/', views.product_search, name='product_search'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
]

store/models.py
import uuid
import secrets
from django.db import models
from django.utils.text import slugify
from cloudinary.models import CloudinaryField
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    class Meta:
        verbose_name_plural = "Categories"

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            self.slug = base_slug
            count = 1
            while Category.objects.filter(slug=self.slug).exists():
                self.slug = f"{base_slug}-{count}"
                count += 1
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("frontend:category_detail", args=[self.slug])
    

class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            self.slug = base_slug
            count = 1
            while Brand.objects.filter(slug=self.slug).exists():
                self.slug = f"{base_slug}-{count}"
                count += 1
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name



class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            self.slug = base_slug
            count = 1
            while Tag.objects.filter(slug=self.slug).exists():
                self.slug = f"{base_slug}-{count}"
                count += 1
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    description = models.TextField(blank=True)
    old_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey('Category', related_name='products', on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag', blank=True, related_name='products')
    brand = models.ForeignKey('Brand', related_name='products', on_delete=models.CASCADE, null=True, blank=True)
    image = CloudinaryField('image', null=True, default=None, blank=True)
    is_available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(default=0, help_text="Rate from 1 (worst) to 5 (best)")

    def generate_unique_slug(self):
        base_slug = slugify(self.name)
        slug = base_slug
        while Product.objects.filter(slug=slug).exists():
            unique_part = f"{uuid.uuid4().hex[:4]}-{secrets.token_hex(2)}"
            slug = f"{unique_part}-{base_slug}"
        return slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super().save(*args, **kwargs)


    @property
    def sale_percent(self):
        if self.old_price and self.old_price > self.price:
            discount = ((self.old_price - self.price) / self.old_price) * 100
            return round(discount, 1)  # Rounded to 1 decimal
        return 0

    def __str__(self):
        return self.name

store/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from store.models import Product

def store(request):
    product_list = Product.objects.all()

    # Pagination: 9 products per page (you can change this)
    paginator = Paginator(product_list, 12)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context = {
        'products':products
    }
    return render(request, 'store/store.html', context)


def product_search(request):
    query = request.GET.get('q', '')
    products = Product.objects.none()

    if query:
        products = Product.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query) |
            Q(category__name__icontains=query) |
            Q(brand__name__icontains=query) |
            Q(tags__name__icontains=query)
        ).distinct()

    return render(request, 'store/product_search_results.html', {'products': products, 'query': query})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)

    related_products = Product.objects.filter(
        category=product.category
    ).exclude(id=product.id)[:5]  # limit to 4

    context = {
        'product': product,
        'related_products': related_products
    }
    return render(request, 'store/product_detail.html', context)

templates/store/product_search_results.html
{% extends '../frontend/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Store | All Products{% endblock %}

{% block content %}
<!--breadcrumbs area start-->
<div class="breadcrumbs_area commun_bread">
    <div class="container">   
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <h3>Search Results for {{ query }}</h3>
                    <ul>
                        <li><a href="{% url 'frontend:home' %}">home</a></li>
                        <li><i class="fa fa-angle-right"></i></li>
                        <li>search</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>         
</div>
<!--breadcrumbs area end-->


<!-- <h1>Search Results for "{{ query }}"</h1>

{% if products %}
    <ul>
    {% for product in products %}
        <li><a href="{{ product.get_absolute_url }}">{{ product.name }}</a> - {{ product.price }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No products found.</p>
{% endif %} -->


<!--shop wrapper start-->
<div class="shop_wrapper shop_fullwidth">
    <div class="container">
         <!--shop toolbar start-->
        <div class="row">
            <div class="col-12">
                <div class="shop_toolbar">

                    <div class="list_button">
                        <ul class="nav" role="tablist">
                            <li>
                                <a class="active" data-bs-toggle="tab" href="#large" role="tab" aria-controls="large" aria-selected="true"><i class="ion-grid"></i></a>
                            </li>
                            <li>
                                <a data-bs-toggle="tab" href="#list" role="tab" aria-controls="list" aria-selected="false"><i class="ion-android-menu"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>        
        <!--shop toolbar end-->
        {% if products %}               
         <!--shop tab product-->
        <div class="shop_tab_product">   
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="large" role="tabpanel">
                    <div class="row">
                        {% for product in products %}
                        <div class="col-lg-3 col-md-4 col-sm-6">
                            <div class="single_product"> 
                                <div class="product_thumb">
                                     <a href="product-details.html"><img src="{{product.image.url}}" alt=""></a>
                                     <div class="btn_quickview">
                                         <a href="#" data-bs-toggle="modal" data-bs-target="#modal_box"  title="Quick View"><i class="ion-ios-eye"></i></a>
                                    </div>
                                </div> 
                                <div class="product_content">   
                                    <div class="product_ratting">
                                        <ul>
                                            {% for i in "12345" %}
                                                {% if forloop.counter <= product.rating %}
                                                <li><a href="#"><i class="ion-star"></i></a></li>
                                                {% else %}
                                                <li><a href="#"><i class="ion-ios-star-outline"></i></a></li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <h3><a href="product-details.html">{{product.name|truncatechars:60}}</a></h3>
                                    <div class="product_price">
                                        <span class="current_price">&#8358;{{product.price|intcomma}}</span>
                                    </div>
                                    <div class="product_action">
                                        <ul>
                                            <li class="product_cart"><a href="cart.html" title="Add to Cart">Add to Cart</a></li>
                                        </ul>
                                    </div>
                                </div>    
                            </div>
                        </div>
                        {% empty %}
                        <p>No product to display. add products</p>
                        {% endfor %}
                    </div>     
                </div>
                <div class="tab-pane fade" id="list" role="tabpanel">
                    {% for product in products %}
                    <div class="single_product list_item">
                        <div class="row align-items-center">   
                            <div class="col-lg-3 col-md-5">
                                <div class="product_thumb">
                                     <a href="product-details.html"><img src="{{product.image.url}}" alt=""></a>
                                     <div class="btn_quickview">
                                         <a href="#" data-bs-toggle="modal" data-bs-target="#modal_box"  title="Quick View"><i class="ion-ios-eye"></i></a>
                                    </div>
                                </div> 
                            </div>
                            <div class="col-lg-9 col-md-7">
                                <div class="product_content">   
                                    <div class="product_ratting">
                                        <ul>
                                            {% for i in "12345" %}
                                                {% if forloop.counter <= product.rating %}
                                                <li><a href="#"><i class="ion-star"></i></a></li>
                                                {% else %}
                                                <li><a href="#"><i class="ion-ios-star-outline"></i></a></li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <h3><a href="product-details.html">{{product.name}}</a></h3>
                                    <div class="product_price">
                                        <span class="current_price">>&#8358;{{product.price|intcomma}}</span>
                                    </div>
                                    <div class="product_description">
                                        <p>{{product.description|truncatechars:280}}</p>
                                    </div>
                                    <div class="product_action">
                                        <ul>
                                            <li class="product_cart"><a href="cart.html" title="Add to Cart">Add to Cart</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div> 
                    </div>   
                    {% empty %}
                    <p>No product to display. add products</p>
                    {% endfor %}                  
                </div>

            </div>
        </div>  
        {% else %}
            <p>No products found.</p>
        {% endif %}  
        <!--shop tab product end-->
        
        <!--pagination style start--> 
        <div class="row">
            <div class="col-12">  
                <!-- pagination style start -->
                {% if products.has_other_pages %}
                <div class="pagination_style fullwidth">
                    <ul>
                        {% if products.has_previous %}
                            <li><a href="?page={{ products.previous_page_number }}">«</a></li>
                        {% else %}
                            <li class="disabled">«</li>
                        {% endif %}

                        {% for num in products.paginator.page_range %}
                            {% if products.number == num %}
                                <li class="current_number">{{ num }}</li>
                            {% else %}
                                <li><a href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if products.has_next %}
                            <li><a href="?page={{ products.next_page_number }}">»</a></li>
                        {% else %}
                            <li class="disabled">»</li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}
                <!-- pagination style end -->
            </div>      
        </div>
        <!--pagination style end-->    
        
    </div>
</div>
<!--shop wrapper end-->

<!-- shipping list -->
{% include '../frontend/partials/shipping.html' %}
<!-- shipping list end -->
{% endblock %}

templates/store/store.html
{% extends '../frontend/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Store | All Products{% endblock %}

{% block content %}
<!--breadcrumbs area start-->
<div class="breadcrumbs_area">
    <div class="container">   
        <div class="breadcrumbs_inner">  
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb_content">
                        <h3>Store</h3>
                        <ul>
                            <li><a href="{% url 'frontend:home' %}">home</a></li>
                            <li><i class="fa fa-angle-right"></i></li>
                            <li>Store</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>         
</div>
<!--breadcrumbs area end-->


<!--shop wrapper start-->
<div class="shop_wrapper shop_fullwidth">
    <div class="container">
         <!--shop toolbar start-->
        <div class="row">
            <div class="col-12">
                <div class="shop_toolbar">

                    <div class="list_button">
                        <ul class="nav" role="tablist">
                            <li>
                                <a class="active" data-bs-toggle="tab" href="#large" role="tab" aria-controls="large" aria-selected="true"><i class="ion-grid"></i></a>
                            </li>
                            <li>
                                <a data-bs-toggle="tab" href="#list" role="tab" aria-controls="list" aria-selected="false"><i class="ion-android-menu"></i></a>
                            </li>
                        </ul>
                    </div>
                    <!-- <div class="select_option number">
                        <form action="#">
                            <label>Show:</label>
                            <select name="orderby" id="short">
                                <option selected value="1">9</option>
                                <option value="1">19</option>
                                <option value="1">30</option>
                            </select>
                        </form>
                    </div>
                    <div class="select_option">
                        <form action="#">
                            <label>Sort By</label>
                            <select name="orderby" id="short1">
                                <option selected value="1">Position</option>
                                <option value="1">Price: Lowest</option>
                                <option value="1">Price: Highest</option>
                                <option value="1">Product Name:Z</option>
                                <option value="1">Sort by price:low</option>
                                <option value="1">Product Name: Z</option>
                                <option value="1">In stock</option>
                                <option value="1">Product Name: A</option>
                                <option value="1">In stock</option>
                            </select>
                        </form>
                    </div> -->
                </div>
            </div>
        </div>        
        <!--shop toolbar end-->
                
         <!--shop tab product-->
        <div class="shop_tab_product">   
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="large" role="tabpanel">
                    <div class="row">
                        {% for product in products %}
                        <div class="col-lg-3 col-md-4 col-sm-6">
                            <div class="single_product"> 
                                <div class="product_thumb">
                                     <a href="{% url 'store:product_detail' product.slug %}"><img src="{{product.image.url}}" alt=""></a>
                                     <div class="btn_quickview">
                                         <a href="{% url 'store:product_detail' product.slug %}" title="Quick View"><i class="ion-ios-eye"></i></a>
                                    </div>
                                </div> 
                                <div class="product_content">   
                                    <div class="product_ratting">
                                        <ul>
                                            {% for i in "12345" %}
                                                {% if forloop.counter <= product.rating %}
                                                <li><a href="#"><i class="ion-star"></i></a></li>
                                                {% else %}
                                                <li><a href="#"><i class="ion-ios-star-outline"></i></a></li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <h3><a href="{% url 'store:product_detail' product.slug %}">{{product.name|truncatechars:40}}</a></h3>
                                    <div class="product_price">
                                        <span class="current_price">&#8358;{{product.price|intcomma}}</span>
                                    </div>
                                    <div class="product_action">
                                        <ul>
                                            <li class="product_cart">
                                                <form onsubmit="addToCart(event, this, '{{ product.slug }}')" class="d-inline">
                                                    {% csrf_token %}
                                                    <input type="number" name="quantity" value="1" min="1" style="width: 50px;">
                                                    <button type="submit" class="btn btn-primary" data-product-slug="{{ product.slug }}">
                                                        <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                                                        <span class="btn-text">Add to Cart</span>
                                                    </button>
                                                </form>
                                            </li>
                                        </ul>
                                    </div>
                                </div>    
                            </div>
                        </div>
                        {% empty %}
                        <p>No product to display. add products</p>
                        {% endfor %}
                    </div>     
                </div>
                <div class="tab-pane fade" id="list" role="tabpanel">
                    {% for product in products %}
                    <div class="single_product list_item">
                        <div class="row align-items-center">   
                            <div class="col-lg-3 col-md-5">
                                <div class="product_thumb">
                                     <a href="{% url 'store:product_detail' product.slug %}"><img src="{{product.image.url}}" alt=""></a>
                                     <div class="btn_quickview">
                                         <a href="{% url 'store:product_detail' product.slug %}" title="Quick View"><i class="ion-ios-eye"></i></a>
                                    </div>
                                </div> 
                            </div>
                            <div class="col-lg-9 col-md-7">
                                <div class="product_content">   
                                    <div class="product_ratting">
                                        <ul>
                                            {% for i in "12345" %}
                                                {% if forloop.counter <= product.rating %}
                                                <li><a href="#"><i class="ion-star"></i></a></li>
                                                {% else %}
                                                <li><a href="#"><i class="ion-ios-star-outline"></i></a></li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <h3><a href="{% url 'store:product_detail' product.slug %}">{{product.name}}</a></h3>
                                    <div class="product_price">
                                        <span class="current_price">>&#8358;{{product.price|intcomma}}</span>
                                    </div>
                                    <div class="product_description">
                                        <p>{{product.description|truncatechars:280}}</p>
                                    </div>
                                    <div class="product_action">
                                        <ul>
                                            <li class="product_cart">
                                                <form onsubmit="addToCart(event, this, '{{ product.slug }}')" class="d-inline">
                                                    {% csrf_token %}
                                                    <input type="number" name="quantity" value="1" min="1" style="width: 50px;">
                                                    <button type="submit" class="btn btn-primary" data-product-slug="{{ product.slug }}">
                                                        <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                                                        <span class="btn-text">Add to Cart</span>
                                                    </button>
                                                </form>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div> 
                    </div>   
                    {% empty %}
                    <p>No product to display. add products</p>
                    {% endfor %}                  
                </div>

            </div>
        </div>    
        <!--shop tab product end-->
        
        <!--pagination style start--> 
        <div class="row">
            <div class="col-12">  
                <!-- pagination style start -->
                {% if products.has_other_pages %}
                <div class="pagination_style fullwidth">
                    <ul>
                        {% if products.has_previous %}
                            <li><a href="?page={{ products.previous_page_number }}">«</a></li>
                        {% else %}
                            <li class="disabled">«</li>
                        {% endif %}

                        {% for num in products.paginator.page_range %}
                            {% if products.number == num %}
                                <li class="current_number">{{ num }}</li>
                            {% else %}
                                <li><a href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if products.has_next %}
                            <li><a href="?page={{ products.next_page_number }}">»</a></li>
                        {% else %}
                            <li class="disabled">»</li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}
                <!-- pagination style end -->
            </div>      
        </div>
        <!--pagination style end-->    
        
    </div>
</div>
<!--shop wrapper end-->


<!-- shipping list -->
{% include '../frontend/partials/shipping.html' %}
<!-- shipping list end -->
{% endblock %}